"use client";

import { useState, useEffect, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { PenTool, Layers, AlertCircle, Sparkles, FolderGit2, Loader2, Download } from "lucide-react";
import { useRepository } from "@/lib/RepositoryContext";
import mermaid from "mermaid";

interface ArchData {
  mermaid_diagram: string;
  tech_stack: string[];
  architecture_summary: string;
  issues: string[];
}

const Mermaid = ({ chart }: { chart: string }) => {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    // Attempt realistic / napkin-inspired styling using properties
    mermaid.initialize({
      startOnLoad: false,
      theme: 'dark',
      fontFamily: '"Comic Sans MS", "Marker Felt", "Inter", sans-serif',
      flowchart: {
        curve: 'basis', // smoother, hand-drawn look
        nodeSpacing: 50,
        rankSpacing: 50,
      },
      themeVariables: {
        primaryColor: 'rgba(139, 92, 246, 0.15)', // violet tint
        primaryBorderColor: 'rgba(139, 92, 246, 0.8)',
        lineColor: 'rgba(255, 255, 255, 0.4)',
        textColor: '#f3f4f6',
        mainBkg: 'rgba(0,0,0,0.5)',
        nodeBorder: 'rgba(255,255,255,0.7)',
        clusterBkg: 'rgba(255,255,255,0.02)',
        clusterBorder: 'rgba(255,255,255,0.2)'
      }
    });

    const renderChart = async () => {
      if (containerRef.current) {
        try {
          containerRef.current.innerHTML = ""; // Clear existing
          
          // Force strip any markdown code blocks the LLM might have returned
          const cleanedChart = chart.replace(/```mermaid/gi, "").replace(/```/g, "").trim();
          
          // Generate a highly unique ID to prevent React StrictMode double rendering collisions
          const id = `mermaid-chart-${Math.random().toString(36).substring(2, 9)}`;
          const { svg } = await mermaid.render(id, cleanedChart);
          containerRef.current.innerHTML = svg;
        } catch (e) {
          console.error("Mermaid parsing error:", e);
          containerRef.current.innerHTML = "<p class='text-red-400 text-sm'>Error parsing diagram graph. The AI generated invalid Mermaid syntax.</p>";
        }
      }
    };
    
    renderChart();
  }, [chart]);

  return <div ref={containerRef} id="mermaid-container" className="w-full flex justify-center py-6 overflow-auto" />;
};

export default function ArchitecturePage() {
  const { repositories } = useRepository();
  const [selectedRepo, setSelectedRepo] = useState("");
  const [loading, setLoading] = useState(false);
  const [archData, setArchData] = useState<ArchData | null>(null);

  const generateDiagram = async () => {
    if (!selectedRepo) return;
    setLoading(true);
    setArchData(null);

    try {
      const BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL || "http://127.0.0.1:8000";
      const res = await fetch(`${BACKEND_URL}/api/architecture/generate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ repo_name: selectedRepo }),
      });

      if (res.ok) {
        const data = await res.json();
        setArchData(data);
      } else {
        alert("Failed to evaluate completely.");
      }
    } catch (error) {
      console.error(error);
      alert("Error reaching AI Architect Engine.");
    } finally {
      setLoading(false);
    }
  };

  const downloadPNG = () => {
      // Find the SVG generated by mermaid inside our container
      const svgEl = document.querySelector("#mermaid-container svg");
      if (!svgEl) return;
      
      const svgData = new XMLSerializer().serializeToString(svgEl);
      const canvas = document.createElement("canvas");
      const ctx = canvas.getContext("2d");
      const img = new Image();
      
      img.onload = () => {
          // Increase resolution for clarity
          canvas.width = img.width * 2;
          canvas.height = img.height * 2;
          
          if(ctx) {
              ctx.scale(2, 2);
              // Draw dark background directly into PNG for visibility
              ctx.fillStyle = "#111116"; 
              ctx.fillRect(0, 0, img.width, img.height);
              ctx.drawImage(img, 0, 0);
          }
          
          const a = document.createElement("a");
          a.download = `${selectedRepo}-Architecture.png`;
          a.href = canvas.toDataURL("image/png");
          a.click();
      };
      
      img.src = "data:image/svg+xml;base64," + btoa(unescape(encodeURIComponent(svgData)));
  };

  return (
    <div className="max-w-6xl mx-auto space-y-8 pb-12">
      {/* Header */}
      <div className="text-center space-y-4">
        <div className="inline-flex items-center justify-center p-3 bg-indigo-500/10 rounded-2xl mb-2 border border-indigo-500/20">
          <PenTool className="w-10 h-10 text-indigo-400" />
        </div>
        <h1 className="text-4xl font-bold tracking-tight" style={{ color: "var(--text-primary)" }}>
          AI Architecture Canvas
        </h1>
        <p className="text-lg mx-auto max-w-xl" style={{ color: "var(--text-secondary)" }}>
          Automatically map your entire codebase into a clean, 'Napkin-style' System Design diagram. Identify dependencies, bottlenecks, and layers instantly.
        </p>
      </div>

      {/* Control Panel */}
      <motion.div 
        className="max-w-md mx-auto p-4 rounded-3xl border"
        style={{ backgroundColor: "var(--card-bg)", borderColor: "var(--border-primary)" }}
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <div className="space-y-4">
          <div className="flex items-center gap-3 p-3 rounded-xl bg-black/20 border border-white/5">
            <FolderGit2 className="w-5 h-5 text-indigo-400" />
            <select
              value={selectedRepo}
              onChange={(e) => setSelectedRepo(e.target.value)}
              className="w-full bg-transparent outline-none font-medium appearance-none"
              style={{ color: "var(--text-primary)" }}
            >
              <option value="" disabled style={{ color: "black" }}>Select your repository...</option>
              {repositories.map(r => (
                <option key={r.id} value={r.name} style={{ color: "black" }}>{r.name}</option>
              ))}
            </select>
          </div>
          
          <button
            onClick={generateDiagram}
            disabled={loading || !selectedRepo}
            className="w-full h-12 flex items-center justify-center gap-2 rounded-xl font-bold transition-all text-white disabled:opacity-50 hover:opacity-90 shadow-xl shadow-indigo-500/20"
            style={{ background: "linear-gradient(135deg, #4f46e5, #4338ca)" }}
          >
            {loading ? <Loader2 className="w-5 h-5 animate-spin" /> : <Sparkles className="w-5 h-5" />}
            {loading ? "Reverse Engineering Layers..." : "Generate Napkin Sketch"}
          </button>
        </div>
      </motion.div>

      {/* Canvas Area */}
      <AnimatePresence>
        {archData && !loading && (
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            className="grid grid-cols-1 lg:grid-cols-3 gap-6 mt-8"
          >
            {/* Visual Diagram Layer */}
            <div 
                className="lg:col-span-2 p-8 rounded-3xl border relative overflow-hidden flex flex-col"
                style={{ 
                    backgroundColor: "#111116", // Specific dark slate for whiteboard effect 
                    borderColor: "rgba(255,255,255,0.05)",
                    boxShadow: "inset 0 0 100px rgba(79, 70, 229, 0.05)"
                }}
            >
                {/* Header Action */}
                <div className="flex justify-between items-center mb-6 pl-2">
                    <div className="flex items-center gap-2">
                        <Layers className="w-5 h-5 text-indigo-400" />
                        <h2 className="font-bold tracking-widest uppercase text-sm text-gray-300">System Design Canvas</h2>
                    </div>
                    <button 
                         onClick={downloadPNG}
                         className="px-4 py-2 bg-white/5 hover:bg-white/10 rounded-lg text-xs font-bold text-gray-300 transition flex items-center gap-2 border border-white/10"
                    >
                         <Download className="w-3 h-3"/> Download PNG
                    </button>
                </div>
                
                {/* SVG Renderer Area */}
                <div className="flex-1 border border-dashed border-white/10 rounded-2xl bg-[#0a0a0d] flex items-center justify-center p-4 relative cursor-crosshair">
                     {/* Subtly grainy dot pattern simulated via bg */}
                     <div className="absolute inset-0 opacity-[0.03]" style={{ backgroundImage: 'radial-gradient(circle, #fff 1px, transparent 1px)', backgroundSize: '20px 20px' }}></div>
                     <div className="relative z-10 w-full">
                        <Mermaid chart={archData.mermaid_diagram} />
                     </div>
                </div>
            </div>

            {/* Smart Insights Panel */}
            <div className="flex flex-col gap-4">
                
                {/* Tech Stack */}
                <div className="p-6 rounded-3xl bg-black/20 border border-white/5 shadow-xl shadow-black/50">
                     <h3 className="text-sm font-black text-gray-300 tracking-widest uppercase mb-4 opacity-80 border-b border-white/5 pb-2">Identified Tech Stack</h3>
                     <div className="flex flex-wrap gap-2">
                         {archData.tech_stack.map((ts, idx) => (
                             <span key={idx} className="px-3 py-1.5 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-xs font-bold text-indigo-300">
                                 {ts}
                             </span>
                         ))}
                     </div>
                </div>

                {/* Architecture Summary */}
                <div className="p-6 rounded-3xl bg-black/20 border border-white/5 shadow-xl shadow-black/50">
                     <h3 className="text-sm font-black text-gray-300 tracking-widest uppercase mb-4 opacity-80 border-b border-white/5 pb-2">Analysis</h3>
                     <p className="text-sm text-gray-400 leading-relaxed font-medium">
                         {archData.architecture_summary}
                     </p>
                </div>

                {/* Risks / Issues */}
                <div className="p-6 rounded-3xl border shadow-xl shadow-black/50 bg-red-500/5 border-red-500/10 flex-1">
                     <h3 className="flex items-center gap-2 text-sm font-black text-red-400 tracking-widest uppercase mb-4 opacity-90 border-b border-red-500/10 pb-2">
                         <AlertCircle className="w-4 h-4" /> Risk Overlay
                     </h3>
                     <ul className="space-y-3">
                         {archData.issues.map((issue, idx) => (
                             <li key={idx} className="flex items-start gap-2 text-sm text-gray-400">
                                 <div className="w-1.5 h-1.5 rounded-full bg-red-500/50 mt-1.5 shrink-0" />
                                 <span className="leading-snug">{issue}</span>
                             </li>
                         ))}
                         {archData.issues.length === 0 && (
                            <li className="text-sm text-gray-500">No major architectural flaws detected.</li>
                         )}
                     </ul>
                </div>

            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
